#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path

from generate_probe_surrogates import expand_probe_sites, flatten_manifest_entries, render_source
from validate_probe_spec import normalize_spec, parse_yaml_subset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prepare a user-facing Omniprobe probe bundle from a v1 probe spec. "
            "The bundle contains generated surrogate source, a manifest, helper "
            "wrapper source, compiled helper bitcode, and an env snippet that "
            "can be fed directly to Omniprobe's existing pass/runtime hooks."
        )
    )
    parser.add_argument("spec", help="Probe spec YAML file")
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory for generated bundle artifacts",
    )
    parser.add_argument(
        "--hipcc",
        default=os.environ.get("HIPCC", "/opt/rocm/bin/hipcc"),
        help="hipcc executable to use for helper compilation",
    )
    parser.add_argument(
        "--arch",
        default=os.environ.get("HIP_ARCH"),
        help="Target GPU architecture, for example gfx90a",
    )
    parser.add_argument(
        "--extra-include",
        action="append",
        default=[],
        help="Additional include directory for helper compilation",
    )
    return parser.parse_args()


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def resolve_helper_source(spec_path: Path, spec: dict[str, object]) -> Path:
    helper_source = Path(str(spec["helpers"]["source"]))
    if helper_source.is_absolute():
        return helper_source
    return (spec_path.parent / helper_source).resolve()


def quoted_include(path: Path) -> str:
    escaped = str(path).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_bundle_outputs(
    spec_path: Path,
    spec: dict[str, object],
    output_dir: Path,
) -> tuple[Path, Path, Path, Path]:
    sites = expand_probe_sites(spec)
    manifest_entries = flatten_manifest_entries(sites)
    surrogate_path = output_dir / "generated_probe_surrogates.hip"
    manifest_path = output_dir / "generated_probe_manifest.json"
    helper_wrapper_path = output_dir / "generated_probe_bundle.hip"
    env_path = output_dir / "generated_probe_env.sh"

    surrogate_path.write_text(
        render_source(spec, sites, manifest_entries), encoding="utf-8"
    )
    manifest_path.write_text(
        json.dumps(
            {
                "version": spec["version"],
                "helpers": spec["helpers"],
                "defaults": spec["defaults"],
                "surrogates": manifest_entries,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    helper_source = resolve_helper_source(spec_path, spec)
    helper_wrapper_path.write_text(
        "\n".join(
            [
                "// Generated by tools/probes/prepare_probe_bundle.py",
                "#include <stdint.h>",
                f"#include {quoted_include(surrogate_path)}",
                f"#include {quoted_include(helper_source)}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    env_path.write_text(
        "\n".join(
            [
                "# Generated by tools/probes/prepare_probe_bundle.py",
                f"export OMNIPROBE_PROBE_MANIFEST={shlex.quote(str(manifest_path))}",
                f"export OMNIPROBE_PROBE_BITCODE={shlex.quote(str(output_dir / 'generated_probe_helpers.bc'))}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return surrogate_path, manifest_path, helper_wrapper_path, env_path


def compile_helper_bitcode(
    *,
    hipcc: str,
    arch: str,
    helper_wrapper: Path,
    output_dir: Path,
    extra_includes: list[str],
) -> tuple[Path, Path]:
    if not arch:
        raise SystemExit("--arch is required (or set HIP_ARCH)")

    toolchain = Path(hipcc)
    if not toolchain.exists():
        raise SystemExit(f"hipcc not found at {hipcc}")

    root = repo_root()
    helper_bc = output_dir / "generated_probe_helpers.bc"
    compile_log = output_dir / "generated_probe_helpers.compile.log"
    include_dirs = [
        root / "external/dh_comms/include",
        root / "inc",
        output_dir,
        helper_wrapper.parent,
    ]
    include_dirs.extend(Path(entry).resolve() for entry in extra_includes)

    command = [
        str(toolchain),
        "-x",
        "hip",
        "--offload-device-only",
        f"--offload-arch={arch}",
        "-fgpu-rdc",
        "-emit-llvm",
        "-c",
    ]
    for include_dir in include_dirs:
        command.extend(["-I", str(include_dir)])
    command.extend(["-o", str(helper_bc), str(helper_wrapper)])

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        check=False,
    )
    compile_log.write_text(
        (result.stdout or "") + (result.stderr or ""),
        encoding="utf-8",
    )
    if result.returncode != 0:
        raise SystemExit(
            "helper bitcode compilation failed; see "
            f"{compile_log}"
        )
    return helper_bc, compile_log


def main() -> int:
    args = parse_args()
    spec_path = Path(args.spec).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    document = parse_yaml_subset(spec_path.read_text(encoding="utf-8"))
    spec = normalize_spec(document)
    helper_source = resolve_helper_source(spec_path, spec)
    if not helper_source.exists():
        raise SystemExit(f"helper source not found: {helper_source}")

    surrogate_path, manifest_path, helper_wrapper_path, env_path = write_bundle_outputs(
        spec_path, spec, output_dir
    )
    helper_bc, compile_log = compile_helper_bitcode(
        hipcc=args.hipcc,
        arch=str(args.arch) if args.arch else "",
        helper_wrapper=helper_wrapper_path,
        output_dir=output_dir,
        extra_includes=list(args.extra_include),
    )

    bundle_report = {
        "version": spec["version"],
        "spec": str(spec_path),
        "helper_source": str(helper_source),
        "surrogate_source": str(surrogate_path),
        "manifest": str(manifest_path),
        "helper_wrapper": str(helper_wrapper_path),
        "helper_bitcode": str(helper_bc),
        "compile_log": str(compile_log),
        "env_script": str(env_path),
        "environment": {
            "OMNIPROBE_PROBE_MANIFEST": str(manifest_path),
            "OMNIPROBE_PROBE_BITCODE": str(helper_bc),
        },
    }
    (output_dir / "generated_probe_bundle.json").write_text(
        json.dumps(bundle_report, indent=2) + "\n",
        encoding="utf-8",
    )
    json.dump(bundle_report, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
